version: '3.8'
services:
  database:
    image: ghcr.io/srueda99/postgres-db:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dummy
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: ghcr.io/srueda99/fastapi-backend:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=dummy
    depends_on:
      - database
  frontend:
    image: ghcr.io/srueda99/react-frontend:latest
    container_name: nginx-frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
volumes:
  postgres_data: