FROM node:24-alpine

# Set working directory
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm install
# Copy the source code
COPY . .
# Switch to a non-root user
USER node
# Expose Vite port
EXPOSE 5173
# Run the app
CMD ["npm", "run", "dev", "--", "--host"]