name: Frontend CI (React)

on:
  push:
    branches: ["master"]
    paths:
      - "app/Front/**"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/react-frontend

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # Copies the code from the repo to the runner
      - name: Checkout
        uses: actions/checkout@v4
      # Creates and boots a builder to be used in the following steps
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      # Authenticates into de Docker Registry (GitHub Container Registry)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REG_TOKEN }}
      # Gets the commit ID
      - name: Get ID
        run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> $GITHUB_ENV
      # Builds the image locally
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: ./app/Front
          load: true
          build-args: |
            API_URL=${{ secrets.API_URL }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # Scans the image for vulnerabilities using Trivy
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      # Pushes the image to Registry
      - name: Push Image
        # Push only if the image passed the security scan
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./app/Front
          push: true
          build-args: |
            API_URL=${{ secrets.API_URL }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
