name: Database CI (PostgreSQL)

on:
  push:
    branches: ["master"]
    paths:
      - "app/DB/**"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/postgres-db

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # Copies the code from the repo to the runner
      - name: Checkout
        uses: actions/checkout@v4
      # Creates and boots a builder to be used in the following steps
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      # Authenticates into de Docker Registry (GitHub Container Registry)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REG_TOKEN }}
      # Gets the commit ID
      - name: Get ID
        run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> $GITHUB_ENV
      # Builds the image locally
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: ./app/DB
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./app/DB
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
